CREATE TABLE "TimeEntry" (
  "TimeEntryID" SERIAL PRIMARY KEY,
  "TaskID" INT NOT NULL,
  "StartTime " TIMESTAMP NOT NULL,
  "EndTime" TIMESTAMP NOT NULL,
  "Notes" VARCHAR(500),
  FOREIGN KEY ("TaskID") REFERENCES "Task"("TaskID")
);

